-- MySQL Script generated by MySQL Workbench
-- Sun Apr 12 18:54:06 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Korisnik`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Korisnik` (
  `idKorisnika` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(50) NOT NULL,
  `password` VARCHAR(50) NOT NULL,
  `email` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`idKorisnika`),
  UNIQUE INDEX `username_UNIQUE` (`username` ASC) VISIBLE,
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE);


-- -----------------------------------------------------
-- Table `mydb`.`Admin`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Admin` (
  `idAdmina` INT NOT NULL,
  PRIMARY KEY (`idAdmina`),
  CONSTRAINT `R_8`
    FOREIGN KEY (`idAdmina`)
    REFERENCES `mydb`.`Korisnik` (`idKorisnika`)
    ON DELETE CASCADE);


-- -----------------------------------------------------
-- Table `mydb`.`Koktel`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Koktel` (
  `idKoktela` INT NOT NULL AUTO_INCREMENT,
  `idKorisnika` INT NOT NULL,
  `naziv` VARCHAR(50) NOT NULL,
  `opis` TEXT NOT NULL,
  `slika` VARCHAR(100) NULL DEFAULT NULL,
  `video` VARCHAR(100) NULL DEFAULT NULL,
  `obrisan` TINYINT NOT NULL,
  `datum` DATE NOT NULL,
  PRIMARY KEY (`idKoktela`),
  UNIQUE INDEX `XAK1Koktel` (`idKorisnika` ASC) VISIBLE,
  CONSTRAINT `R_1`
    FOREIGN KEY (`idKorisnika`)
    REFERENCES `mydb`.`Korisnik` (`idKorisnika`));


-- -----------------------------------------------------
-- Table `mydb`.`Registrovani`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Registrovani` (
  `idRegistrovanog` INT NOT NULL,
  `obrisanNalog` TINYINT NOT NULL,
  PRIMARY KEY (`idRegistrovanog`),
  CONSTRAINT `R_9`
    FOREIGN KEY (`idRegistrovanog`)
    REFERENCES `mydb`.`Korisnik` (`idKorisnika`)
    ON DELETE CASCADE);


-- -----------------------------------------------------
-- Table `mydb`.`Prijava`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Prijava` (
  `idKoktela` INT NOT NULL,
  `datum` DATE NOT NULL,
  `idRegistrovanog` INT NOT NULL,
  `obrisanaPrijava` TINYINT NOT NULL,
  PRIMARY KEY (`idKoktela`, `idRegistrovanog`),
  INDEX `R_10` (`idRegistrovanog` ASC) VISIBLE,
  CONSTRAINT `R_5`
    FOREIGN KEY (`idKoktela`)
    REFERENCES `mydb`.`Koktel` (`idKoktela`),
  CONSTRAINT `R_10`
    FOREIGN KEY (`idRegistrovanog`)
    REFERENCES `mydb`.`Registrovani` (`idRegistrovanog`));


-- -----------------------------------------------------
-- Table `mydb`.`Razlog`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Razlog` (
  `idRazloga` INT NOT NULL AUTO_INCREMENT,
  `opisRazloga` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`idRazloga`));


-- -----------------------------------------------------
-- Table `mydb`.`RazloziPrijave`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`RazloziPrijave` (
  `idRazloga` INT NOT NULL,
  `idKoktela` INT NOT NULL,
  `idRegistrovanog` INT NOT NULL,
  `duplikat` VARCHAR(100) NULL DEFAULT NULL,
  PRIMARY KEY (`idRazloga`, `idKoktela`, `idRegistrovanog`),
  INDEX `R_13` (`idKoktela` ASC, `idRegistrovanog` ASC) VISIBLE,
  CONSTRAINT `R_12`
    FOREIGN KEY (`idRazloga`)
    REFERENCES `mydb`.`Razlog` (`idRazloga`),
  CONSTRAINT `R_13`
    FOREIGN KEY (`idKoktela` , `idRegistrovanog`)
    REFERENCES `mydb`.`Prijava` (`idKoktela` , `idRegistrovanog`));


-- -----------------------------------------------------
-- Table `mydb`.`Sastojak`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Sastojak` (
  `idSastojka` INT NOT NULL AUTO_INCREMENT,
  `naziv` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`idSastojka`));


-- -----------------------------------------------------
-- Table `mydb`.`SadrziNeobavezno`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`SadrziNeobavezno` (
  `kolicina` VARCHAR(50) NOT NULL,
  `idKoktela` INT NOT NULL,
  `idSastojka` INT NOT NULL,
  PRIMARY KEY (`idKoktela`, `idSastojka`),
  INDEX `R_16` (`idSastojka` ASC) VISIBLE,
  CONSTRAINT `R_15`
    FOREIGN KEY (`idKoktela`)
    REFERENCES `mydb`.`Koktel` (`idKoktela`),
  CONSTRAINT `R_16`
    FOREIGN KEY (`idSastojka`)
    REFERENCES `mydb`.`Sastojak` (`idSastojka`));


-- -----------------------------------------------------
-- Table `mydb`.`SadrziObavezno`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`SadrziObavezno` (
  `idKoktela` INT NOT NULL,
  `idSastojka` INT NOT NULL,
  `kolicina` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`idKoktela`, `idSastojka`),
  INDEX `R_3` (`idSastojka` ASC) VISIBLE,
  CONSTRAINT `R_2`
    FOREIGN KEY (`idKoktela`)
    REFERENCES `mydb`.`Koktel` (`idKoktela`),
  CONSTRAINT `R_3`
    FOREIGN KEY (`idSastojka`)
    REFERENCES `mydb`.`Sastojak` (`idSastojka`));


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
